apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: b82nt0g4g-nodejs 
  janus-idp.io/tekton: b82nt0g4g-nodejs
  backstage.io/kubernetes-id: b82nt0g4g-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: b82nt0g4g-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml