apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: b82nt0g4g-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: b82nt0g4g-nodejs 
  name: b82nt0g4g-nodejs
spec:
  port:
    targetPort: 3001 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: b82nt0g4g-nodejs
    weight: 100 
