apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: b82nt0g4g-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: b82nt0g4g-nodejs 
  name: b82nt0g4g-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: b82nt0g4g-nodejs 
